### ISSUE TITLE
Run this script for second time, it still run slurp and get an area to record.

### ISSUE THREAD

**Issue by ffs-akl** [Vescrity/wfrc#1]
Archlinux+lxqt(wayland session)+labwc,  the second runing did not stop recording as expected.

**Comment by Vescrity** [comment]
Sorry for delayed reply. I forgot to update my script.   

Please try the new one.

**Comment by ffs-akl** [comment]
Ok, I will try.   
I have an idea: could it be simply via wfterst='ps -A | grep wf-recorder'
if [ -n wftest ]; then
pkill wf-recorder
else
..............
fi

**Comment by Vescrity** [comment]
It might be OK i think. But if any other programs start a wf-recorder can cause a problem I think.   

Anyway, this time i use pid to kill the process. I think it can be a good way to solve the problem.

**Comment by ffs-akl** [comment]
your are right!  Thank you for your patience in explaining.

**Comment by ffs-akl** [comment]
the script work fine now.
an random idea: if turn the lock file into a variable, the script don't have to write an file to the hard disk. 
IMO, a program should write as few data to the hard drive as possible.
If you disagree, please feel free to ignore it.

**Comment by Vescrity** [comment]
I don't know about other distros, but `/tmp` on Arch is on tmpfs by default, which write the data in your memory but not hard drive.   

And in order to make the second run can kill the process of the first run, I don't know how to make it possible through variable as there seems not have a way to share it through different processes.

Edit: maybe dbus can, but it's hard for me.
